method: grid
metric:
  goal: maximize
  name: r2_score
name: KNN
parameters:
  algorithm:
    values:
    - auto
    - ball_tree
    - kd_tree
    - brute
  metric: 
    values:
    - euclidean
    - manhattan
    - minkowski
  model_type:
    value: KNN
  n_neighbors:
    values:
    - 3
    - 5
    - 7
    - 9
    - 11
  weights:
    values:
    - uniform
    - distance
program: sweep.py
