version: "3.8"

networks:
  front-tier:
  back-tier:

services:
  backend:
    build:
      context: ./flask_backend
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      - MLFLOW_URL=http://host.docker.internal:5000
      - PREFECT_URL=http://host.docker.internal:4200
    ports:
      - "6969:6969"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - back-tier

  frontend:
    build:
      context: ./stremlit_frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:6969
    ports:
      - "8501:8501"
    networks:
      - front-tier
      - back-tier