version: "3.8"

networks:
  front-tier:
  back-tier:

volumes:
    postgres_data: {}


services:
  backend:
    build:
      context: ./flask_backend
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      - MLFLOW_URL=http://host.docker.internal:5000
      - PREFECT_URL=http://host.docker.internal:4200
      - POSTGRES_URL=http://database:5432
    ports:
      - "6969:6969"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - back-tier
    depends_on:
      - database

  frontend:
    build:
      context: ./stremlit_frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:6969
    ports:
      - "8501:8501"
    networks:
      - front-tier
      - back-tier

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - back-tier
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier
      - front-tier  